name = "WR-Testpack"
author = "Egassy, Anna"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45ae49456c33e3fcab70f84b063c32282bb11c1f63362b891154ace1a038d895"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
unsup = "1.2.7"
