name = "WR-Testpack"
author = "Egassy, Anna"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e156b702cfb54719274e5db5e8f58fa0fc7633d791b0120f7f80e018ac3d234f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
unsup = "1.2.7"
